import Head from "next/head";
import ProductsPage from "./ProductsPage/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Profile-Company</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="widith=device-widith, initial-scale=1" />
      </Head>
      <main className="bg-white">
        <div>
          <ProductsPage />
        </div>
      </main>
    </div>
  );
}
